### PR TITLE
Created second page and routing

### PR DESCRIPTION
**Pull request by DanielAgbeni**
Created the second page, added routing when log in button is clicked 
Added AOS animation on all pages for presentable animation
fixed horizontal scroll from bug homepage
Change Twitter icon to new twitter X icon
 
1st page
2nd page pc
mobile 2nd

### CODE REVIEW

**Comment by nobledeveloper01** [comment]
pls merge this so that i can pick my assigned issue from here

**Comment by nobledeveloper01** [comment]
pls merge this so that i can pick my assigned issue from here

**Comment by DanielAgbeni** [comment]
I am not the maintainer maybe you should add it in the whatsapp group

**Comment by nobledeveloper01** [comment]
Ok boss, I know you are not the maintainer, just haste them

**Pull request merged**
