### PR TITLE
layout bug fix

### PR DESCRIPTION
**Pull request by Glory135**
fixed a home page layout bug caused from conflicting codes

### CODE REVIEW

**Comment by gray-adeyi** [comment]
In this your new fix.. the App component wasn't used. I'm not really sure how things should be I'd have merged it but @Elijah699 will review and merge it

**Comment by Glory135** [comment]
Okay

**Comment by Glory135** [comment]
The App component was used in index.js

**Comment by gray-adeyi** [comment]
No quite. The project doesn't seem to have an `index.js` but then I could be wrong...just wait for @Elijah699. I work mainly on the backend. Nice work btw 👍🏿

**Comment by Glory135** [comment]
sorry i meant main.jsx

**Comment by Glory135** [comment]
okay thanks

**Pull request merged**
