### PR TITLE
Built Header and Made it responsive

### PR DESCRIPTION
**Pull request by DanielAgbeni**
Libraries installed
Framer motion
React Icons

### CODE REVIEW

**Comment by DanielAgbeni** [comment]
Fixed #11

**Comment by nobledeveloper01** [comment]
Nice one @DanielAgbeni

**Comment by nobledeveloper01** [comment]
i think you forgot the login button

**Comment by Elijah699** [comment]
Nice job @DanielAgbeni.

**Comment by DanielAgbeni** [comment]
I will see to dat ASAP

**Pull request merged**
